name: CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.11'
  PACKAGE_NAME: 'ansys-conceptev-core'
  DOCUMENTATION_CNAME: 'conceptev.docs.pyansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:


  vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys vulnerability check
        if: github.ref != 'refs/heads/main'
        uses: ansys/actions/check-vulnerabilities@fix/inconsistent-behavior
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys code style checks
        uses: ansys/actions/code-style@fix/inconsistent-behavior
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  tests:
    name: Tests and coverage
    runs-on: ${{ matrix.os }}
    needs: [smoke-tests]
    strategy:
      matrix:
       os: [ubuntu-latest]
       python-version: ["3.11"]
      fail-fast: false
    steps:
      - uses: ansys/actions/tests-pytest@fix/inconsistent-behavior
        env:
          POETRY_VIRTUALENVS_CREATE: ${{ vars.POETRY_VIRTUALENVS_CREATE }}
        with:
          pytest-extra-args: "-m 'not integration' --cov=ansys --cov-report=term --cov-report=html:.cov/html"

  doc-build:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: [doc-style]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install texlive-latex-extra texlive-xetex texlive-fonts-extra
          # sudo apt-get install libgl1-mesa-glx xvfb texlive-latex-extra latexmk graphviz texlive-xetex texlive-fonts-extra qpdf texlive-xetex xindy

      - name: Verify Pandoc installation
        run: pandoc --version

      - name: Build documentation
        env:
          CONCEPTEV_USERNAME: ${{ secrets.CONCEPTEV_USERNAME }}
          CONCEPTEV_PASSWORD: ${{ secrets.CONCEPTEV_PASSWORD }}
        uses: ansys/actions/doc-build@fix/inconsistent-behavior
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          check-links: false
